# Generated by Django 4.1 on 2024-06-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libreria", "0003_genero_libro_generos"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de Actualización"
            ),
        ),
    ]
