# Generated by Django 4.1 on 2024-06-09 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libreria", "0004_libro_fecha_actualizacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libro",
            name="generos",
        ),
    ]
