# Generated by Django 4.1 on 2024-06-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libreria", "0006_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
