# Generated by Django 4.1 on 2024-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libreria", "0008_alter_libro_descripcion_alter_libro_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="pdfs/", verbose_name="Archivo PDF"
            ),
        ),
    ]
