# Generated by Django 4.1 on 2024-06-16 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("libreria", "0009_libro_pdf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libro",
            name="pdf",
        ),
    ]
