# Generated by Django 4.1 on 2024-06-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("libreria", "0010_remove_libro_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="libro",
            name="pdf",
            field=models.FileField(
                blank=True, null=True, upload_to="pdfs/", verbose_name="Archivo PDF"
            ),
        ),
    ]
